package cli

import (
	"fmt"
	"log"
	"os/exec"
	"strings"

	"github.com/spf13/cobra"

	"github.com/jessn-dev/sprout/internal/generator"
)

// flags for `sprout new`
var (
	fName, fGroup, fArtifact, fPackage, fDesc         string
	fBuild, fLanguage, fPackaging, fJava, fBoot, fTyp string
	fDeps                                             []string
	fGit                                              bool
)

var newCmd = &cobra.Command{
	Use:   "new",
	Short: "Generate a project non-interactively from flags",
	Long:  "Generate a Spring Boot project entirely from flags — no TUI. Ideal for scripts and CI.",
	Example: `  sprout new --name shop-api --group com.acme --deps web,data-jpa,docker
  sprout new --name api --type security --java 21 --git`,
	Run: func(cmd *cobra.Command, args []string) {
		artifact := fArtifact
		if artifact == "" {
			artifact = fName
		}
		pkg := fPackage
		if pkg == "" {
			pkg = fGroup + "." + strings.ReplaceAll(artifact, "-", "")
		}

		cfg := generator.Config{
			BuildTool:   fBuild,
			Language:    fLanguage,
			BootVersion: fBoot,
			GroupId:     fGroup,
			ArtifactId:  artifact,
			Name:        fName,
			Description: fDesc,
			PackageName: pkg,
			Packaging:   fPackaging,
			JavaVersion: fJava,
			ProjectType: fTyp,
			Deps:        fDeps,
		}

		if err := generator.ValidateConfig(cfg); err != nil {
			log.Fatal(err)
		}

		fmt.Printf("\n🌱 Generating '%s'...\n", cfg.Name)
		if err := generator.Generate(cfg); err != nil {
			log.Fatalf("Failed to generate project: %v", err)
		}

		dir := generator.FolderName(cfg)
		if fGit {
			gitInit(dir)
		}
		printNextSteps(dir)
	},
}

func init() {
	newCmd.Flags().StringVar(&fName, "name", "demo", "project name")
	newCmd.Flags().StringVar(&fGroup, "group", "com.example", "group ID")
	newCmd.Flags().StringVar(&fArtifact, "artifact", "", "artifact ID (defaults to name)")
	newCmd.Flags().StringVar(&fPackage, "package", "", "package name (defaults to group.artifact)")
	newCmd.Flags().StringVar(&fDesc, "desc", "Generated by Sprout", "project description")
	newCmd.Flags().StringVar(&fBuild, "build", "maven-project", "build tool: maven-project|gradle-project|gradle-project-kotlin")
	newCmd.Flags().StringVar(&fLanguage, "language", "java", "language: java|kotlin|groovy")
	newCmd.Flags().StringVar(&fPackaging, "packaging", "jar", "packaging: jar|war")
	newCmd.Flags().StringVar(&fJava, "java", "21", "Java version")
	newCmd.Flags().StringVar(&fBoot, "boot", "", "Spring Boot version (empty = server default)")
	newCmd.Flags().StringVar(&fTyp, "type", "standard", "profile: standard|cloud|security (empty = none)")
	newCmd.Flags().StringSliceVar(&fDeps, "deps", nil, "comma-separated dependency IDs (e.g. web,data-jpa,docker)")
	newCmd.Flags().BoolVar(&fGit, "git", false, "run 'git init' in the generated project")

	rootCmd.AddCommand(newCmd)
}

func gitInit(dir string) {
	cmd := exec.Command("git", "init")
	cmd.Dir = dir
	if err := cmd.Run(); err != nil {
		fmt.Printf("⚠️  git init failed: %v\n", err)
		return
	}
	fmt.Println("✓ Initialized empty git repository")
}

func printNextSteps(dir string) {
	fmt.Printf("\n📂 Next steps:\n")
	fmt.Printf("   cd %s\n", dir)
	fmt.Printf("   ./mvnw spring-boot:run   # or ./gradlew bootRun\n")
}
